### ISSUE TITLE
Firebase - Data Layer

### ISSUE THREAD

**Issue by samirraza09** [CMPUT301F22T13/GROUP13-MEAL-PLANNING-PROJECT#47]
- [ ] FirebaseDL.java
- [x] IngredientDL.java
- [x] RecipeDL.java

- [ ] Implement Unit Tests - Should have unit test coverage for firebase DL

Get a firebase connection going for the project, add functionality to delete and add these items, also research how to get login and signup working in firebase. Look into using a 3rd party like sign-in with google.

Adding some more encapsulation in the firebase DL
- [ ] Build up recipies data layer

**Comment by Irehmani** [comment]
Add, Delete, Update and Get - items to work on.

**Comment by Irehmani** [comment]
Image storage using URL firebase

**Comment by Irehmani** [comment]
Implementing link list for add, delete, update and view ingredients and recepies

**Comment by Irehmani** [comment]
Implementing UML

**Comment by Irehmani** [comment]
Have another varaible in recepies and ingredients representing the unique has associated with each value

**Comment by Irehmani** [comment]
Add Java Doc
