### ISSUE TITLE
Comments for Project Part 2

### ISSUE THREAD

**Issue by hamzaMAlvi** [CMPUT301F22T13/GROUP13-MEAL-PLANNING-PROJECT#58]
#### If necessary make new issues relevant to the comments and link them to this issue (make them a subtask of this issue). If you have any confusion mention me in the comments section of this issue along with the question.
---

@Irehmani @ScottGebert @samirraza09 @albuquer-ualberta @shivchopra @thimerlogan 

---
### Marks
3/3
### Comments
Some things can be improved in using the tools. Ask TA regarding this matter.

---

### Marks
2/3
### Comments
✓ Requirements are very comprehensive and thoroughly tracked, well done
✓ Story point estimates are complete and reasonable
✓ Risk levels are complete and reasonable
✘ Requirements not noted for half-way checkpoint

- [ ] #74

---

### Marks
2/3
### Comments
1. Every class should not have userid. It can be stored in the user class.
2. Ingredient class should not have the recipe, ingredient storage, Meal Plan,
 Shopping List and DBService classes to do its task. Similarly, ingredient storage 
do not need the Shopping List class to its task. Similarly, there are wrong collaborators
list for other classes. Correct the collaborator list for all the classes.
3. Class name contains space like ""Meal Plan"". Follow the naming convention.
• Clear, readable, consistent, and organized: See comments
• Covers key classes: Yes
• Complete responsibilities: See comments
• Complete collaborators: See comments
• Object-oriented: Yes
• Cohesive classes: Yes
• Coupling managed: Yes

- [x] #76

---

### Marks
3/3
### Comments
• Consistent and clear: no, It is difficult to follow storyboard
• Complete UI mockups: yes, at start page remove the footer and place those things in the screen
• Labeled elements on UI mockups: yes
• Detailed storyboard: yes
• Labeled actions for storyboard transitions: yes
• Covers all requirements: yes
• Intuitive user interface: yes
• Displays understanding of UI mockups and storyboarding: mostly
Ask the TA in the next meeting for detailed list of improvements that can be made

- [x] #75

**Comment by samirraza09** [comment]
For " Requirements not noted for half-way checkpoint" we did do this. We used milestone in user stories.

![Capture](https://user-images.githubusercontent.com/71533292/198842683-575e1899-4efe-4160-aaf7-70479f1e551e.PNG)

**Comment by hamzaMAlvi** [comment]
> For " Requirements not noted for half-way checkpoint" we did do this. We used milestone in user stories.
> 
> ![Capture](https://user-images.githubusercontent.com/71533292/198842683-575e1899-4efe-4160-aaf7-70479f1e551e.PNG)

I have informed the marking TA.
