### ISSUE TITLE
Adding Recipe relevant methods and attributes in UML

### ISSUE THREAD

**Issue by albuquer-ualberta** [CMPUT301F22T13/GROUP13-MEAL-PLANNING-PROJECT#62]
![image](https://user-images.githubusercontent.com/71734306/198857488-49dc6785-14b9-46b3-9b28-1789a089e506.png)

Wherever "Ingredient" or "Ingredients" is seen, it needs to be changed to "Recipe" or "Recipes".

**Comment by ScottGebert** [comment]
Done
