### ISSUE TITLE
Sorting Comparators for IngredientItem

### ISSUE THREAD

**Issue by thimerlogan** [CMPUT301F22T13/GROUP13-MEAL-PLANNING-PROJECT#64]
- [x] Description comparable
- [ ] Best before date comparable
- [ ] Location comparable
- [x] Category comparable

Implement in the ingredientItem.java

**Comment by ScottGebert** [comment]
Waiting on @albuquer-ualberta to add bbfd and location to ingredient item - alternatively I can add them but want to avoid merge conflicts
